### PR TITLE
Add example to selective sync in the README

### PR DESCRIPTION
**Pull request by jonnius**

### CODE REVIEW

**Comment by jonnius** [comment]
> [Coverage Status](https://coveralls.io/builds/19330925)
> 
> Coverage decreased (-5.009%) to 46.831% when pulling **[21e091b](https://github.com/xybu/onedrived-dev/commit/21e091be471158ba773fc102d047d8184fb63f41) on jonnius:master** into **[4f24e4f](https://github.com/xybu/onedrived-dev/commit/4f24e4f3b2344ef5cdd9d167913bf32e6419a39b) on xybu:master**.

What does that mean?

**Comment by jakebrinkmann** [comment]
@jonnius since I had to dig in to find it out, I think you should mention where this information should be placed, e.g.

```markdown
# When creating a new drive, include a Drive Specific ignore file
onedrived-pref drive set --ignore-file TEXT
```

(RE:"Coverage Decreased" the project must not ignore *.md files, and because of that your addition of text reduced the overall percentage of the project covered by unit-testing. Notice the CodeCov report shows no change, which seems more accurate)

**Comment by jonnius** [comment]
@jakebrinkmann sorry for replying late. Would you like to improve it yourself?

**Comment by jakebrinkmann** [comment]
@jonnius no worries, I only wanted to provide you some feedback for consideration. I found your modification helpful, so thank you!

**Pull request merged**
